// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

namespace StudentAPI.Data.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("StudentLibrary.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BcitID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityOfResidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "bf4c9d70-3872-43ec-ba45-d252ff792bd8",
                            BcitID = "A00123456",
                            CityOfResidence = "Chilliwack",
                            EmailAddress = "jim@potter.com",
                            FirstName = "Jim",
                            LastName = "Potter",
                            MobileNumber = "604-123-4567",
                            Specialization = "Nursing"
                        },
                        new
                        {
                            Id = "627d709d-502e-4a72-ba84-cf3c09381407",
                            BcitID = "A00000001",
                            CityOfResidence = "Vancouver",
                            EmailAddress = "aa@aa.aa",
                            FirstName = "Jane",
                            LastName = "Douglas",
                            MobileNumber = "111-111-1111",
                            Specialization = "Computing"
                        },
                        new
                        {
                            Id = "98ee1f83-5ddd-4a9e-9dbb-fff0fddb12b2",
                            BcitID = "A00000002",
                            CityOfResidence = "Abbotsford",
                            EmailAddress = "bb@bb.bb",
                            FirstName = "Tom",
                            LastName = "Gardner",
                            MobileNumber = "222-222-2222",
                            Specialization = "Business"
                        },
                        new
                        {
                            Id = "9611f8ed-4ba3-40f5-aab2-25bc088fac17",
                            BcitID = "A00000003",
                            CityOfResidence = "Surrey",
                            EmailAddress = "cc@cc.cc",
                            FirstName = "Ann",
                            LastName = "Lee",
                            MobileNumber = "333-333-3333",
                            Specialization = "Aircraft Maintenance"
                        },
                        new
                        {
                            Id = "bacb5700-ea46-4d64-9970-53f06786e911",
                            BcitID = "A00000004",
                            CityOfResidence = "Burnaby",
                            EmailAddress = "dd@dd.dd",
                            FirstName = "James",
                            LastName = "Jones",
                            MobileNumber = "444-444-4444",
                            Specialization = "Marketing"
                        },
                        new
                        {
                            Id = "56d76f0b-1a98-4788-99cc-a935d1f22b77",
                            BcitID = "A00000005",
                            CityOfResidence = "Vancouver",
                            EmailAddress = "ee@ee.ee",
                            FirstName = "Susan",
                            LastName = "Taylor",
                            MobileNumber = "555-555-5555",
                            Specialization = "Pilot"
                        },
                        new
                        {
                            Id = "706c2c4e-ee96-46c6-b44d-efed6579bb75",
                            BcitID = "A00000006",
                            CityOfResidence = "Coquitlam",
                            EmailAddress = "ff@ff.ff",
                            FirstName = "Peter",
                            LastName = "White",
                            MobileNumber = "666-666-6666",
                            Specialization = "Engineering"
                        },
                        new
                        {
                            Id = "66333f72-32e6-43bd-99b3-1bf848baa8c3",
                            BcitID = "A00000007",
                            CityOfResidence = "North-Vancouver",
                            EmailAddress = "gg@gg.gg",
                            FirstName = "Philip",
                            LastName = "Fox",
                            MobileNumber = "777-777-7777",
                            Specialization = "Instructor"
                        },
                        new
                        {
                            Id = "8f4dae03-d0f2-439d-8587-04b7f447e2f4",
                            BcitID = "A00000008",
                            CityOfResidence = "West-Vancouver",
                            EmailAddress = "hh@hh.hh",
                            FirstName = "Donna",
                            LastName = "Ray",
                            MobileNumber = "888-888-8888",
                            Specialization = "Instructor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
