// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentAPI.Data;

namespace StudentAPI.Data.Migrations
{
    [DbContext(typeof(StudentDbContext))]
    partial class StudentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("StudentLibrary.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("BcitID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CityOfResidence")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = "202eec22-94a0-4074-b6e0-e598199bd609",
                            BcitID = "A00123456",
                            CityOfResidence = "Chilliwack",
                            EmailAddress = "jim@potter.com",
                            FirstName = "Jim",
                            LastName = "Potter",
                            MobileNumber = "604-123-4567",
                            Specialization = "Nursing"
                        },
                        new
                        {
                            Id = "eaa799f2-e4dd-4036-8f48-2154990c2cf1",
                            BcitID = "A00000001",
                            CityOfResidence = "Vancouver",
                            EmailAddress = "aa@aa.aa",
                            FirstName = "Jane",
                            LastName = "Douglas",
                            MobileNumber = "111-111-1111",
                            Specialization = "Computing"
                        },
                        new
                        {
                            Id = "f75258b0-c5d4-402f-925c-68cb959570d7",
                            BcitID = "A00000002",
                            CityOfResidence = "Abbotsford",
                            EmailAddress = "bb@bb.bb",
                            FirstName = "Tom",
                            LastName = "Gardner",
                            MobileNumber = "222-222-2222",
                            Specialization = "Business"
                        },
                        new
                        {
                            Id = "31b8d2fa-ca07-42ce-9dc2-1743195af2b3",
                            BcitID = "A00000003",
                            CityOfResidence = "Surrey",
                            EmailAddress = "cc@cc.cc",
                            FirstName = "Ann",
                            LastName = "Lee",
                            MobileNumber = "333-333-3333",
                            Specialization = "Aircraft Maintenance"
                        },
                        new
                        {
                            Id = "2b7be063-83fa-4460-bd72-09e9f7eb44a8",
                            BcitID = "A00000004",
                            CityOfResidence = "Burnaby",
                            EmailAddress = "dd@dd.dd",
                            FirstName = "James",
                            LastName = "Jones",
                            MobileNumber = "444-444-4444",
                            Specialization = "Marketing"
                        },
                        new
                        {
                            Id = "a1ee517c-30ab-48f5-b2a0-5a6c0e4d08c7",
                            BcitID = "A00000005",
                            CityOfResidence = "Vancouver",
                            EmailAddress = "ee@ee.ee",
                            FirstName = "Susan",
                            LastName = "Taylor",
                            MobileNumber = "555-555-5555",
                            Specialization = "Pilot"
                        },
                        new
                        {
                            Id = "ece8ffa4-42fc-402e-9ff9-b4275a4a4c11",
                            BcitID = "A00000006",
                            CityOfResidence = "Coquitlam",
                            EmailAddress = "ff@ff.ff",
                            FirstName = "Peter",
                            LastName = "White",
                            MobileNumber = "666-666-6666",
                            Specialization = "Engineering"
                        },
                        new
                        {
                            Id = "3431c40c-9454-4792-900c-03cfb0b8add2",
                            BcitID = "A00000007",
                            CityOfResidence = "North-Vancouver",
                            EmailAddress = "gg@gg.gg",
                            FirstName = "Philip",
                            LastName = "Fox",
                            MobileNumber = "777-777-7777",
                            Specialization = "Instructor"
                        },
                        new
                        {
                            Id = "f1124c6f-4582-49a6-86a1-d95b963a910f",
                            BcitID = "A00000008",
                            CityOfResidence = "West-Vancouver",
                            EmailAddress = "hh@hh.hh",
                            FirstName = "Donna",
                            LastName = "Ray",
                            MobileNumber = "888-888-8888",
                            Specialization = "Instructor"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
